taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
disqusShortname: comunidaddemamas
markup:
  goldmark:
    renderer:
      unsafe: true
title: Comunidad de Mamás
baseURL: https://www.comunidaddemamas.com
params:
  layout_style: overflow
  palette: blue
  header:
    title: Stackbit Fresh
    tagline: Header Tagline
    profile_img: >-
      https://images.ctfassets.net/muz36ont8wk7/2769tqr64g9AwYqFYLrm7u/5f5fdd3d69e45ceb8b5a44e540929386/avatar.png
    profile_img_alt: Author avatar
    background: dark
    has_nav: true
    nav_links:
      - label: Home
        url: /
        style: link
        type: action
      - label: Blog
        url: /blog/
        style: link
        type: action
      - label: Style Guide
        url: /style-guide/
        style: link
        type: action
      - label: About
        url: /about/
        style: link
        type: action
      - label: Contact
        url: /contact/
        style: link
        type: action
    has_social: true
    social_links:
      - label: Twitter
        url: 'https://twitter.com/'
        style: icon
        icon_class: twitter
        new_window: true
        type: action
      - label: Instagram
        url: 'https://www.instagram.com/'
        style: icon
        icon_class: instagram
        new_window: true
        type: action
      - label: GitHub
        url: 'https://github.com/'
        style: icon
        icon_class: github
        new_window: true
        type: action
      - label: LinkedIn
        url: 'https://www.linkedin.com/'
        style: icon
        icon_class: linkedin
        new_window: true
        type: action
      - label: DEV
        url: 'https://dev.to/'
        style: icon
        icon_class: dev
        new_window: true
        type: action
    type: header
  footer:
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created with
      <a href="https://www.stackbit.com/?utm_source=deployed-footer"
      target="_blank" rel="noopener">Stackbit</a>. Create yours <a
      href="https://app.stackbit.com/create?theme=fresh&utm_source=deployed-footer"
      target="_blank" rel="noopener">now</a>
    type: footer
  type: config_params
